### ISSUE TITLE
y_amx_impl.inc error YSI 5.x fast

### ISSUE THREAD

**Issue by skuzzis** [pawn-lang/YSI-Includes#478]
fatal error 104: invalid assembler instruction "load.u.pri"

**Comment by skuzzis** [comment]
i forgot to mention from where is the error: \pawno\include\YSI_Core\y_master\..\..\YSI_Core\y_core\y_amx_impl.inc(892) : fatal error 104: invalid assembler instruction "load.u.pri"

**Comment by Y-Less** [comment]
Hmm, which compiler version are you on?  That relies on the community compiler, but that instruction was only added in 3.10.10 I think.  I should check for that.

**Comment by skuzzis** [comment]
I have zeex comp 3.10.6 i think, and with every zeex comp or crashes, or gives me error

**Comment by Y-Less** [comment]
What error do you get with 3.10.10?

**Comment by skuzzis** [comment]
Wait a second to compile again

**Comment by skuzzis** [comment]
if I compile with 3.10.10 it gave me these warnings and error with y_amx_impl.inc:
\pawno\include\YSI_Visual\y_commands\..\..\YSI_Data\y_foreach\..\..\YSI_Coding\y_va\..\..\YSI_Core\y_core\..\..\indirection\indirection.inc(84) : warning 201: redefinition of constant/macro (symbol "GLOBAL_TAG_TYPES")
\pawno\include\YSI_Coding\y_timers\..\y_malloc\y_malloc_warning.inc(8) : warning 237: user warning: y_malloc heap allocation is unstable.  Use `YSI_NO_HEAP_MALLOC` to disable it, or `YSI_YES_HEAP_MALLOC` to disable this warning: git.io/YSI_HEAP_MALLOC

**Comment by skuzzis** [comment]
with heap_malloc i know the warning but with y_amx_impl.inc and indirection.inc i don't know the solution

**Comment by Y-Less** [comment]
The others I know, but I'm going to add extra checks because people keep getting that indirection warning because they aren't on the latest version.  I'll have to double-check the error, maybe I built with an experimental compiler build.

**Comment by skuzzis** [comment]
@Y-Less something new?
